version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: me-api-postgres
    environment:
      POSTGRES_DB: me_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:

